title: "My Site"
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache

# Load custom CSS
defaults:
  - scope:
      path: ""
    values:
      custom_css:
        - /assets/css/custom.css
